# Generated by Django 5.2.8 on 2025-11-27 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='foto',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
