# Generated by Django 5.2.17 on 2026-09-14 17:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoLoja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_loja", models.CharField(default="Administra", max_length=120)),
                (
                    "slogan",
                    models.CharField(
                        blank=True, default="Sistema de Gestão", max_length=160
                    ),
                ),
                ("cnpj", models.CharField(blank=True, max_length=18)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="loja/")),
                ("cor_primaria", models.CharField(default="#1570EF", max_length=7)),
                ("simbolo_moeda", models.CharField(default="R$", max_length=5)),
                (
                    "permite_estoque_negativo",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, permite vender sem saldo em estoque.",
                    ),
                ),
                (
                    "baixa_estoque_em_orcamento",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, orçamentos também reservam estoque.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração da Loja",
                "verbose_name_plural": "Configuração da Loja",
            },
        ),
        migrations.CreateModel(
            name="ProdutoVariacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="SKU da Variação"
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "tamanho",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: P, M, G, 38, 42.",
                        max_length=30,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "cor",
                    models.CharField(blank=True, max_length=30, verbose_name="Cor"),
                ),
                ("descricao_extra", models.CharField(blank=True, max_length=60)),
                (
                    "preco_venda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deixe em branco para usar o preço do produto.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Preço próprio (opcional)",
                    ),
                ),
                (
                    "quantidade_estoque",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=12
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Variação de Produto",
                "verbose_name_plural": "Variações de Produto",
                "ordering": ["produto__nome", "tamanho", "cor"],
            },
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["nome"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="papel",
            field=models.CharField(
                choices=[
                    ("PROPRIETARIO", "Proprietário"),
                    ("GERENTE", "Gerente"),
                    ("OPERADOR", "Operador de Caixa"),
                    ("ESTOQUISTA", "Estoquista"),
                ],
                default="OPERADOR",
                max_length=20,
                verbose_name="papel",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="ativo",
            field=models.BooleanField(
                default=True, verbose_name="Disponível para venda"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Código de Barras (EAN/GTIN)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="controla_estoque",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para serviços e itens sem controle de saldo.",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="incremento_venda",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                help_text="Passo permitido na quantidade. Ex.: 0,050 para múltiplos de 50 g.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Incremento de venda",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade_minima_venda",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                help_text="Ex.: 0,100 para vender a partir de 100 g.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantidade mínima por venda",
            ),
        ),
        migrations.AlterField(
            model_name="movimentoestoque",
            name="custo_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Custo Unitário",
            ),
        ),
        migrations.AlterField(
            model_name="movimentoestoque",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="custo",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Preço de Custo",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantidade_estoque",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                verbose_name="Quantidade em Estoque",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantidade_minima_alerta",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("5.000"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Qtd. Mínima para Alerta",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("UN", "Unidade (un)"),
                    ("PC", "Peça (pç)"),
                    ("CX", "Caixa (cx)"),
                    ("PCT", "Pacote (pct)"),
                    ("DZ", "Dúzia (dz)"),
                    ("KG", "Quilograma (kg)"),
                    ("G", "Grama (g)"),
                    ("L", "Litro (L)"),
                    ("ML", "Mililitro (mL)"),
                    ("M", "Metro (m)"),
                    ("CM", "Centímetro (cm)"),
                    ("M2", "Metro quadrado (m²)"),
                    ("M3", "Metro cúbico (m³)"),
                    ("H", "Hora (h)"),
                ],
                default="UN",
                max_length=4,
                verbose_name="Vendido por",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="venda",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Preço de Venda",
            ),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["nome"], name="contas_prod_nome_02254d_idx"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["sku"], name="contas_prod_sku_a204c6_idx"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(
                fields=["codigo_barras"], name="contas_prod_codigo__09cb40_idx"
            ),
        ),
        migrations.AddField(
            model_name="produtovariacao",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variacoes",
                to="contas.produto",
            ),
        ),
        migrations.AddField(
            model_name="movimentoestoque",
            name="variacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentos",
                to="contas.produtovariacao",
                verbose_name="Variação",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentoestoque",
            index=models.Index(
                fields=["produto", "-data_movimento"],
                name="contas_movi_produto_bf788c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtovariacao",
            constraint=models.UniqueConstraint(
                fields=("produto", "tamanho", "cor", "descricao_extra"),
                name="variacao_unica_por_produto",
            ),
        ),
    ]
