# Generated by Django 5.2.8 on 2025-11-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='nome fantasia')),
                ('categoria', models.CharField(help_text='Ex: Eletrônicos e Componentes', max_length=255, verbose_name='categoria')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, verbose_name='CNPJ')),
                ('contato_principal', models.CharField(help_text='Nome da pessoa de contato', max_length=255, verbose_name='contato principal')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telefone', models.CharField(help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='telefone')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_fantasia'],
            },
        ),
    ]
