# Generated by Django 5.2.8 on 2025-11-22 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('imagem_categoria', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagem Padrão da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU (Código)')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('quantidade_minima_alerta', models.IntegerField(default=5, verbose_name='Qtd. Mínima para Alerta')),
                ('unidade_medida', models.CharField(blank=True, default='UN', max_length=10, null=True, verbose_name='Unidade de Medida')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ZERADO', 'Estoque Zerado'), ('BAIXO', 'Estoque Baixo')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Ajuste Positivo)'), ('SAIDA', 'Saída (Venda/Ajuste Negativo)')], max_length=10, verbose_name='Tipo de Movimento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
