# Generated by Django 5.2.8 on 2025-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_categoria_produto_movimentoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagem Padrão da Categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima_alerta',
            field=models.IntegerField(default=5, verbose_name='Qtd. Mínima para Alerta'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(default='UN', max_length=10, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ZERADO', 'Estoque Zerado'), ('BAIXO', 'Estoque Baixo')], default='ATIVO', max_length=10, verbose_name='Status'),
        ),
    ]
