# Generated by Django 5.2.8 on 2025-11-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_categoria_produto_movimentoestoque'),
        ('contas', '0002_fornecedor'),
    ]

    operations = [
    ]
