# Generated by Django 5.2.8 on 2025-11-22 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_categoria_imagem_categoria_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
    ]
