# Generated by Django 5.2.8 on 2025-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_movimentoestoque_custo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, default='UN', max_length=10, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
