# Generated by Django 5.2.17 on 2026-09-14 17:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_alter_logacao_options_alter_cliente_cidade_and_more"),
        ("contas", "0002_configuracaoloja_produtovariacao_and_more"),
        ("vendas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemvenda",
            options={
                "verbose_name": "Item da Venda",
                "verbose_name_plural": "Itens da Venda",
            },
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="desconto_item",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="unidade_medida",
            field=models.CharField(
                blank=True,
                help_text="Unidade registrada no momento da venda.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="variacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contas.produtovariacao",
                verbose_name="Variação (tamanho/cor)",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="acrescimo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Acréscimo (R$)",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Desconto (R$)",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="estoque_baixado",
            field=models.BooleanField(
                default=False,
                help_text="Indica se esta venda já retirou os itens do estoque.",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("pix", "PIX"),
                    ("debito", "Cartão de Débito"),
                    ("credito", "Cartão de Crédito"),
                    ("boleto", "Boleto"),
                    ("crediario", "Crediário / Fiado"),
                ],
                default="dinheiro",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_registradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="preco_unitario",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: venda de balcão pode não ter cliente identificado.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["-data_venda", "status"], name="vendas_vend_data_ve_f559c8_idx"
            ),
        ),
    ]
