# Generated by Django 5.2.8 on 2025-11-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf_alter_cliente_valor_total_comprado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PRODUTO', 'Produto'), ('ESTOQUE', 'Estoque'), ('VENDA', 'Venda')], max_length=20)),
                ('entidade_id', models.IntegerField(blank=True, null=True)),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão')], max_length=20)),
                ('descricao', models.TextField()),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
