# Generated by Django 5.2.17 on 2026-09-14 17:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_logacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logacao",
            options={
                "ordering": ["-datahora"],
                "verbose_name": "Log de Ação",
                "verbose_name_plural": "Logs de Ações",
            },
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="valor_total_comprado",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="logacao",
            name="entidade",
            field=models.CharField(
                choices=[
                    ("CLIENTE", "Cliente"),
                    ("PRODUTO", "Produto"),
                    ("ESTOQUE", "Estoque"),
                    ("VENDA", "Venda"),
                    ("FORNECEDOR", "Fornecedor"),
                    ("FUNCIONARIO", "Funcionário"),
                    ("CONFIGURACAO", "Configuração"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logacao",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["nome"], name="clientes_cl_nome_b2cdde_idx"),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["cpf"], name="clientes_cl_cpf_e6905f_idx"),
        ),
        migrations.AddIndex(
            model_name="logacao",
            index=models.Index(
                fields=["-datahora"], name="clientes_lo_datahor_331265_idx"
            ),
        ),
    ]
